# modprobe options
g_ether.conf                            usr/lib/modprobe.d/

# helper scripts/binaries
rpi-usb-gadget                          usr/bin/
ics-watch                               usr/libexec/rpi-usb-gadget/

# Udev Rules
udev/99-rpi-usb-gadget-hint.rules       usr/lib/udev/rules.d/
# Udev Private helper (namespaced)
udev/host_hint.sh                       usr/libexec/rpi-usb-gadget/

# Systemd service
rpi-usb-gadget-ics.service              usr/lib/systemd/system/
